make a file structure
facg3/Hawas-Studio pull request #9
Opened 2018-02-04 14:09 UTC by ismail2009

#6

2018-02-04 17:03 UTC, marwa7med approved these changes

2018-02-05 09:19 UTC, marwa7med approved these changes

2018-02-05 09:19 UTC, marwa7med commented on webpack.config.js
> +    "entry": "./src/frontEnd/index.js",
edit this line "./src/client/index.js"

2018-02-05 09:19 UTC, marwa7med commented on webpack.config.js
> +                            "context": path.resolve("src/frontEnd/assets/")
and this line

2018-02-05 09:19 UTC, NadiaKhatib approved these changes

2018-02-05 10:39 UTC, abdhalees requested changes
remove `styles` folder from `public` since you're using react and making the styles in `client` folder

2018-02-05 10:54 UTC, ismail2009 commented
I move it @abdhalees

2018-02-05 10:57 UTC, abdhalees approved these changes

2018-02-05 10:58 UTC, merged